version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=kien2001vn
    ports:
      - "5432:5432"    
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "85:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    restart: unless-stopped